#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 35

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Reglas para que los dialogos de archivos no se rompan
bspc rule -a Brave state=floating center=on rectangle=800x600+0+0

#GESTION DE ENERGIA Y BLOQUEO ESTO EVITA CONGELE AL CERRAR TAPA DEL PORTATIL
#xss-lock -- i3lock -c 000000 &
light-locker --lock-on-suspend &

#TRASPARENCiA
pkill picom
picom &

#ESTABLECE EL FONDO DE ESCRITORIO
feh --bg-fill /home/linux/Imagenes/wallpapers/peakpx.jpg &

#LANNZAR SCRIPT
$HOME/.config/polybar/launch.sh &
